name: Tests

on:
  pull_request:

jobs:
  ios-tests:
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run post-clone script
        run: bash ci_scripts/ci_post_clone.sh

      - name: Run tests
        run: |
          set -o pipefail
          xcodebuild test \
            -project "Papia.xcodeproj" \
            -scheme "PaÃÅpia" \
            -testPlan "TestPlan" \
            -destination "platform=iOS Simulator,name=iPhone 17 Pro,OS=latest" \
            -configuration Debug
